# @package _global_
defaults:
- _self_
- method: TSVM

model: ViT-B-32
num_tasks: 20
specify_lambda: None

DATASETS: ''
DATASETS_VAL: ''

# utilities
cache_dir: None
world_size: 1
port: 12355
n_eval_points: 31
device: "cuda"
batch_size: 32
data_location: "datasets"
model_location: "./models/checkpoints"
save_subfolder: ""

hydra:
  run:
    dir: ./logs/${model}/${method.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./logs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
