DATASETS: ''
DATASETS_ALL:
- DTD
- GTSRB
- MNIST
- SVHN
- STL10
- OxfordIIITPet
- Flowers102
- CIFAR100
- PCAM
- CIFAR10
- Food101
- FashionMNIST
- RenderedSST2
- EMNIST
- KMNIST
DATASETS_VAL: ''
batch_size: 32
cache_dir: null
data_location: ./datasets
device: cuda
initialize_sigma: average
model: ViT-B-16
model_location: ./models/checkpoints
n_eval_points: 31
num_tasks: 15
sigma_epochs: null
sigma_lr: 1.0e-03
sigma_wd: 0.0
sigma_lr_step_size: 1
sigma_lr_gamma: 0.5
train_k: 0
num_grad_accumulation: 1
adapter: none
adapter_lr: null
adapter_wd: null
config_tag: null
epochs_per_task: 10
port: 12355
svd_keep_topk: 5
world_size: 1
blockwise_coef: true
seed: 1
warmup_ratio: 0.1


